---
#
# Install PostgreSQL
#
- name: PostgreSQLリポジトリの追加
  yum:
    name: "{{ postgresql_yum_repository_url }}"
    state: present

- name: 依存をインストール
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: ["python-psycopg2", "python-pycurl", "glibc-common"]

- name: "インストール {{ postgresql_version_terse }}"
  yum:
    name: "{{ item }}"
    state: present
#  environment: postgresql_env
  with_items:
    - "postgresql{{ postgresql_version_terse }}-server"
    - "postgresql{{ postgresql_version_terse }}-devel"
    - "postgresql{{ postgresql_version_terse }}"

- name: rubyのpg gem用にpg_configをパスに通す
  file:
    src: "{{ postgresql_bin_directory }}/pg_config"
    dest: /usr/bin/pg_config
    state: link
    force: yes
    
